spring:
  application:
    name: api-boot-sample-logging
  profiles:
    active: appoint
server:
  port: 8080

api:
  boot:
    logging:
      format-console-log-json: true
      show-console-log: true
logging:
  level:
    org.minbox.framework.logging: debug
