api:
  boot:
    logging:
      format-console-log-json: true
      number-of-request-log: 2
      discovery:
        service-id: sample-logging-admin
        username: user
        password: 123456
      ignore-paths:
        - /actuator/health

# Eureka Config
eureka:
  client:
    service-url:
      defaultZone: http://service:nodev2@192.168.10.72:10001/eureka/
  instance:
    prefer-ip-address: true