language: java
jdk: openjdk8
node_js: "10"
before_script:
  - npm install
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
    - node_modules
install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -DskipNpmBuild=true