spring:
  application:
    name: api-boot-sample-rate-limiter
  # redis 相关配置
  redis:
    password: 123456

api:
  boot:
    # 配置限流的拦截路径
    rate-limiter:
      interceptor-url: /**
      enable-global-qps: true
      global-qps: 20

# nacos config
nacos:
  config:
    server-addr: 127.0.0.1:8848
